export default Object.freeze({
  ONBOARDING: 'ONBOARDING',
  WELCOME: 'WELCOME',
  FINISH: 'FINISH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT-PASSWORD',
  VERIFY_CODE: 'VERIFY-CODE',
  NEW_PASSWORD: 'NEW-PASSWORD',
});
